export const REDACT_PATHS = [
  'Authorization',
  'Cookie',
  'DATABASE_URL',
  'databaseUrl',
  'accessToken',
  'authorization',
  'cookie',
  'password',
  'refreshToken',
  '*.Authorization',
  '*.Cookie',
  '*.DATABASE_URL',
  '*.databaseUrl',
  '*.accessToken',
  '*.authorization',
  '*.cookie',
  '*.password',
  '*.refreshToken',
  'req.headers.authorization',
  'req.headers.cookie',
] as const;
